
(function () {
    "use strict";

    var dataArray = [
            { title: 'Peru', text: 'Flag', picture: 'images/flags/Peru.png' },
            { title: 'Liberia', text: 'Flag', picture: 'images/flags/Liberia.png' },
            { title: 'Algeria', text: 'Flag', picture: 'images/flags/Algeria.png' },
            { title: 'Belgium', text: 'Flag', picture: 'images/flags/Belgium.png' },
            { title: 'Scotland', text: 'Flag', picture: 'images/flags/Scotland.png' },
            { title: 'Cuba', text: 'Flag', picture: 'images/flags/Cuba.png' },
            { title: 'Greece', text: 'Flag', picture: 'images/flags/Greece.png' },
            { title: 'United-States', text: 'Flag', picture: 'images/flags/United-States.png' },
            { title: 'Czech-Republic', text: 'Flag', picture: 'images/flags/Czech-Republic.png' },
            { title: 'Costa-Rica', text: 'Flag', picture: 'images/flags/Costa-Rica.png' },
            { title: 'Uganda', text: 'Flag', picture: 'images/flags/Uganda.png' },
            { title: 'Austria', text: 'Flag', picture: 'images/flags/Austria.png' },
            { title: 'Barbados', text: 'Flag', picture: 'images/flags/Barbados.png' },
            { title: 'Japan', text: 'Flag', picture: 'images/flags/Japan.png' },
            { title: 'Afghanistan', text: 'Flag', picture: 'images/flags/Afghanistan.png' },
            { title: 'France', text: 'Flag', picture: 'images/flags/France.png' },
            { title: 'United-Arab-Emirates', text: 'Flag', picture: 'images/flags/United-Arab-Emirates.png' },
            { title: 'Singapore', text: 'Flag', picture: 'images/flags/Singapore.png' },
            { title: 'Zimbabwe', text: 'Flag', picture: 'images/flags/Zimbabwe.png' },
            { title: 'Kuwait', text: 'Flag', picture: 'images/flags/Kuwait.png' },
            { title: 'Kenya', text: 'Flag', picture: 'images/flags/Kenya.png' },
            { title: 'Jamaica', text: 'Flag', picture: 'images/flags/Jamaica.png' },
            { title: 'Brazil', text: 'Flag', picture: 'images/flags/Brazil.png' },
            { title: 'England', text: 'Flag', picture: 'images/flags/England.png' },
            { title: 'United-Kingdom', text: 'Flag', picture: 'images/flags/United-Kingdom.png' },
            { title: 'Saudi-Arabia', text: 'Flag', picture: 'images/flags/Saudi-Arabia.png' },
            { title: 'Denmark', text: 'Flag', picture: 'images/flags/Denmark.png' },
            { title: 'Iran', text: 'Flag', picture: 'images/flags/Iran.png' },
            { title: 'Luxembourg', text: 'Flag', picture: 'images/flags/Luxembourg.png' },
            { title: 'Spain', text: 'Flag', picture: 'images/flags/Spain.png' },
            { title: 'Slovakia', text: 'Flag', picture: 'images/flags/Slovakia.png' },
            { title: 'Serbia', text: 'Flag', picture: 'images/flags/Serbia.png' },
            { title: 'Sweden', text: 'Flag', picture: 'images/flags/Sweden.png' },
            { title: 'Ireland', text: 'Flag', picture: 'images/flags/Ireland.png' },
            { title: 'Chile', text: 'Flag', picture: 'images/flags/Chile.png' },
            { title: 'Rwanda', text: 'Flag', picture: 'images/flags/Rwanda.png' },
            { title: 'Ghana', text: 'Flag', picture: 'images/flags/Ghana.png' },
            { title: 'Uruguay', text: 'Flag', picture: 'images/flags/Uruguay.png' },
            { title: 'Qatar', text: 'Flag', picture: 'images/flags/Qatar.png' },
            { title: 'Antarctica', text: 'Flag', picture: 'images/flags/Antarctica.png' },
            { title: 'Netherlands', text: 'Flag', picture: 'images/flags/Netherlands.png' },
            { title: 'Poland', text: 'Flag', picture: 'images/flags/Poland.png' },
            { title: 'Indonesia', text: 'Flag', picture: 'images/flags/Indonesia.png' },
            { title: 'Israel', text: 'Flag', picture: 'images/flags/Israel.png' },
            { title: 'Venezuela', text: 'Flag', picture: 'images/flags/Venezuela.png' },
            { title: 'Jordan', text: 'Flag', picture: 'images/flags/Jordan.png' },
            { title: 'Uzbekistan', text: 'Flag', picture: 'images/flags/Uzbekistan.png' },
            { title: 'Colombia', text: 'Flag', picture: 'images/flags/Colombia.png' },
            { title: 'Turkey', text: 'Flag', picture: 'images/flags/Turkey.png' },
            { title: 'Iceland', text: 'Flag', picture: 'images/flags/Iceland.png' },
            { title: 'Kazakhstan', text: 'Flag', picture: 'images/flags/Kazakhstan.png' },
            { title: 'Portugal', text: 'Flag', picture: 'images/flags/Portugal.png' },
            { title: 'South-Africa', text: 'Flag', picture: 'images/flags/South-Africa.png' },
            { title: 'Myanmar', text: 'Flag', picture: 'images/flags/Myanmar.png' },
            { title: 'Albania', text: 'Flag', picture: 'images/flags/Albania.png' },
            { title: 'China', text: 'Flag', picture: 'images/flags/China.png' },
            { title: 'India', text: 'Flag', picture: 'images/flags/India.png' },
            { title: 'Germany', text: 'Flag', picture: 'images/flags/Germany.png' },
            { title: 'Vatican-City', text: 'Flag', picture: 'images/flags/Vatican-City.png' },
            { title: 'Nepal', text: 'Flag', picture: 'images/flags/Nepal.png' },
            { title: 'Finland', text: 'Flag', picture: 'images/flags/Finland.png' },
            { title: 'Iraq', text: 'Flag', picture: 'images/flags/Iraq.png' },            
            { title: 'Thailand', text: 'Flag', picture: 'images/flags/Thailand.png' },
            { title: 'Vietnam', text: 'Flag', picture: 'images/flags/Vietnam.png' },
            { title: 'Hungary', text: 'Flag', picture: 'images/flags/Hungary.png' },
            { title: 'Australia', text: 'Flag', picture: 'images/flags/Australia.png' },
            { title: 'Ukraine', text: 'Flag', picture: 'images/flags/Ukraine.png' },
            { title: 'Philippines', text: 'Flag', picture: 'images/flags/Philippines.png' },
            { title: 'Sri-Lanka', text: 'Flag', picture: 'images/flags/Sri-Lanka.png' },
            { title: 'Mexico', text: 'Flag', picture: 'images/flags/Mexico.png' },
            { title: 'Argentina', text: 'Flag', picture: 'images/flags/Argentina.png' },
            { title: 'Bangladesh', text: 'Flag', picture: 'images/flags/Bangladesh.png' },
            { title: 'Egypt', text: 'Flag', picture: 'images/flags/Egypt.png' },
            { title: 'Canada', text: 'Flag', picture: 'images/flags/Canada.png' },
            { title: 'Malaysia', text: 'Flag', picture: 'images/flags/Malaysia.png' },
            { title: 'Norway', text: 'Flag', picture: 'images/flags/Norway.png' },
            { title: 'Taiwan', text: 'Flag', picture: 'images/flags/Taiwan.png' },
            { title: 'Hong-Kong', text: 'Flag', picture: 'images/flags/Hong-Kong.png' },
            { title: 'Cambodia', text: 'Flag', picture: 'images/flags/Cambodia.png' },
            { title: 'Switzerland', text: 'Flag', picture: 'images/flags/Switzerland.png' },
            { title: 'Russia', text: 'Flag', picture: 'images/flags/Russia.png' },
            { title: 'Paraguay', text: 'Flag', picture: 'images/flags/Paraguay.png' },
            { title: 'New-Zealand', text: 'Flag', picture: 'images/flags/New-Zealand.png' },
            { title: 'South-Korea', text: 'Flag', picture: 'images/flags/South-Korea.png' },            
            { title: 'Italy', text: 'Flag', picture: 'images/flags/Italy.png' },
    ];

    var dataList = new WinJS.Binding.List(dataArray);

    // Create a namespace to make the data publicly
    // accessible. 
    var publicMembers =
        {
            itemList: dataList 
        };
    WinJS.Namespace.define("DataExample", publicMembers);
})();